# Generated by Django 3.0 on 2021-03-25 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShowAll', models.CharField(blank=True, choices=[('show', 'Show'), ('hide', 'Hide')], default='show', max_length=8, null=True)),
                ('ShowFungi', models.CharField(blank=True, choices=[('show', 'Show'), ('hide', 'Hide')], default='show', max_length=8, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DataFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShowAll', models.CharField(blank=True, choices=[('show', 'Show'), ('hide', 'Hide'), ('unknown', 'Unknown')], default='show', max_length=8, null=True)),
                ('ShowFungi', models.CharField(blank=True, choices=[('show', 'Show'), ('hide', 'Hide'), ('unknown', 'Unknown')], default='show', max_length=8, null=True)),
                ('ShowOtherCommonNames', models.CharField(blank=True, choices=[('show', 'Show'), ('hide', 'Hide'), ('unknown', 'Unknown')], default='show', max_length=8, null=True)),
                ('ShowOtherLatinNames', models.CharField(blank=True, choices=[('show', 'Show'), ('hide', 'Hide'), ('unknown', 'Unknown')], default='show', max_length=8, null=True)),
                ('ShowTaxonomy', models.CharField(blank=True, choices=[('show', 'Show'), ('hide', 'Hide'), ('unknown', 'Unknown')], default='show', max_length=8, null=True)),
                ('ShowPoresAndTubes', models.CharField(blank=True, choices=[('show', 'Show'), ('hide', 'Hide'), ('unknown', 'Unknown')], default='show', max_length=8, null=True)),
                ('ShowGills', models.CharField(blank=True, choices=[('show', 'Show'), ('hide', 'Hide'), ('unknown', 'Unknown')], default='show', max_length=8, null=True)),
                ('ShowSpores', models.CharField(blank=True, choices=[('show', 'Show'), ('hide', 'Hide'), ('unknown', 'Unknown')], default='show', max_length=8, null=True)),
                ('ShowFlesh', models.CharField(blank=True, choices=[('show', 'Show'), ('hide', 'Hide'), ('unknown', 'Unknown')], default='show', max_length=8, null=True)),
                ('ShowHabitat', models.CharField(blank=True, choices=[('show', 'Show'), ('hide', 'Hide'), ('unknown', 'Unknown')], default='show', max_length=8, null=True)),
                ('ShowCuisine', models.CharField(blank=True, choices=[('show', 'Show'), ('hide', 'Hide'), ('unknown', 'Unknown')], default='show', max_length=8, null=True)),
                ('ShowCap', models.CharField(blank=True, choices=[('show', 'Show'), ('hide', 'Hide'), ('unknown', 'Unknown')], default='show', max_length=8, null=True)),
                ('ShowStipe', models.CharField(blank=True, choices=[('show', 'Show'), ('hide', 'Hide'), ('unknown', 'Unknown')], default='show', max_length=8, null=True)),
                ('ShowSeasons', models.CharField(blank=True, choices=[('show', 'Show'), ('hide', 'Hide'), ('unknown', 'Unknown')], default='show', max_length=8, null=True)),
                ('ShowSimilarFungi', models.CharField(blank=True, choices=[('show', 'Show'), ('hide', 'Hide'), ('unknown', 'Unknown')], default='show', max_length=8, null=True)),
                ('ShowStatus', models.CharField(blank=True, choices=[('show', 'Show'), ('hide', 'Hide'), ('unknown', 'Unknown')], default='show', max_length=8, null=True)),
                ('ShowFungiComments', models.CharField(blank=True, choices=[('show', 'Show'), ('hide', 'Hide'), ('unknown', 'Unknown')], default='show', max_length=8, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DataFilter',
                'managed': True,
            },
        ),
    ]
