# Generated by Django 3.0 on 2021-03-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_datafilter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ShowAll',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ShowFungi',
        ),
    ]
