# Generated by Django 3.0 on 2021-04-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showsearchfields',
            name='MonthFound',
            field=models.BooleanField(default=False, verbose_name=' _Month found'),
        ),
    ]
