# Generated by Django 3.0 on 2021-04-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0002_showsearchfields_monthfound'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showsearchfields',
            old_name='CapShapeDescription',
            new_name='CapShape',
        ),
        migrations.RenameField(
            model_name='showsearchfields',
            old_name='Cuisine',
            new_name='CuisineTaste',
        ),
        migrations.RenameField(
            model_name='showsearchfields',
            old_name='PoresAndTubesPoreBruiseColour',
            new_name='PoreBruiseColour',
        ),
        migrations.RenameField(
            model_name='showsearchfields',
            old_name='PoresAndTubesPoreColour',
            new_name='PoreColour',
        ),
        migrations.RenameField(
            model_name='showsearchfields',
            old_name='PoresAndTubesMilk',
            new_name='PoreMilk',
        ),
        migrations.RenameField(
            model_name='showsearchfields',
            old_name='PoresAndTubesPoreShape',
            new_name='PoreShape',
        ),
        migrations.RenameField(
            model_name='showsearchfields',
            old_name='PoresAndTubesPoresPresent',
            new_name='PoresPresent',
        ),
        migrations.RenameField(
            model_name='showsearchfields',
            old_name='PoresAndTubesTubeColour',
            new_name='SporeColour',
        ),
        migrations.RenameField(
            model_name='showsearchfields',
            old_name='PoresAndTubesTubeShape',
            new_name='StipeShape',
        ),
        migrations.RenameField(
            model_name='showsearchfields',
            old_name='PoresAndTubesTubeBruiseColour',
            new_name='TubeBruiseColour',
        ),
        migrations.RenameField(
            model_name='showsearchfields',
            old_name='Spores',
            new_name='TubeColour',
        ),
        migrations.RenameField(
            model_name='showsearchfields',
            old_name='StipeShapeDescription',
            new_name='TubeShape',
        ),
        migrations.RemoveField(
            model_name='showsearchfields',
            name='CapWidthMax',
        ),
        migrations.RemoveField(
            model_name='showsearchfields',
            name='CapWidthMin',
        ),
        migrations.RemoveField(
            model_name='showsearchfields',
            name='StipeCutColour',
        ),
        migrations.RemoveField(
            model_name='showsearchfields',
            name='StipeLengthMax',
        ),
        migrations.RemoveField(
            model_name='showsearchfields',
            name='StipeLengthMin',
        ),
        migrations.RemoveField(
            model_name='showsearchfields',
            name='StipeThicknessMax',
        ),
        migrations.RemoveField(
            model_name='showsearchfields',
            name='StipeThicknessMin',
        ),
        migrations.AddField(
            model_name='showsearchfields',
            name='CapWidth',
            field=models.BooleanField(default=False, verbose_name=' _width'),
        ),
        migrations.AddField(
            model_name='showsearchfields',
            name='StipeLength',
            field=models.BooleanField(default=False, verbose_name=' _length'),
        ),
        migrations.AddField(
            model_name='showsearchfields',
            name='StipeThickness',
            field=models.BooleanField(default=False, verbose_name=' _thickness'),
        ),
    ]
