# Generated by Django 3.0 on 2021-04-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0003_auto_20210421_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='showsearchfields',
            name='StipeCutColour',
            field=models.BooleanField(default=False, verbose_name=' _Cut colour'),
        ),
    ]
