# Generated by Django 3.0 on 2021-04-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0004_showsearchfields_stipecutcolour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showsearchfields',
            name='HabitatPhType',
        ),
        migrations.AlterField(
            model_name='showsearchfields',
            name='PoreBruiseColour',
            field=models.BooleanField(default=False, verbose_name=' _Pore Bruise colour'),
        ),
        migrations.AlterField(
            model_name='showsearchfields',
            name='PoreColour',
            field=models.BooleanField(default=False, verbose_name=' _Pore Colour'),
        ),
        migrations.AlterField(
            model_name='showsearchfields',
            name='PoreShape',
            field=models.BooleanField(default=False, verbose_name=' _PoreShape'),
        ),
        migrations.AlterField(
            model_name='showsearchfields',
            name='PoresPresent',
            field=models.BooleanField(default=False, verbose_name=' _Pores Present'),
        ),
        migrations.AlterField(
            model_name='showsearchfields',
            name='TubeBruiseColour',
            field=models.BooleanField(default=False, verbose_name=' _Tube Bruise colour'),
        ),
        migrations.AlterField(
            model_name='showsearchfields',
            name='TubeColour',
            field=models.BooleanField(default=False, verbose_name=' _Tube Colour'),
        ),
        migrations.AlterField(
            model_name='showsearchfields',
            name='TubeShape',
            field=models.BooleanField(default=False, verbose_name=' _Tube Shape'),
        ),
    ]
