# Generated by Django 3.0 on 2021-04-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0005_auto_20210422_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showsearchfields',
            old_name='CuisinePoisonType',
            new_name='PoisonType',
        ),
    ]
