# Generated by Django 3.0 on 2021-04-27 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0006_auto_20210427_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showsearchfields',
            old_name='CuisineOdour',
            new_name='Odour',
        ),
        migrations.RenameField(
            model_name='showsearchfields',
            old_name='CuisineTaste',
            new_name='Taste',
        ),
    ]
