# Generated by Django 3.0 on 2021-04-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0007_auto_20210427_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showsearchfields',
            old_name='OtherCommonNamesAltCommonName',
            new_name='OtherCommonNames',
        ),
        migrations.RenameField(
            model_name='showsearchfields',
            old_name='OtherLatinNamesAltLatinName',
            new_name='OtherLatinNames',
        ),
    ]
