# Generated by Django 3.0 on 2021-04-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0008_auto_20210427_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showsearchfields',
            old_name='TaxonomyKlass',
            new_name='TaxonomyClass',
        ),
    ]
