# Generated by Django 3.0 on 2021-04-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0009_auto_20210427_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showsearchfields',
            old_name='TaxonomyClass',
            new_name='Class',
        ),
        migrations.RenameField(
            model_name='showsearchfields',
            old_name='TaxonomyFamily',
            new_name='Family',
        ),
        migrations.RenameField(
            model_name='showsearchfields',
            old_name='TaxonomyPhyum',
            new_name='Kingdom',
        ),
        migrations.RenameField(
            model_name='showsearchfields',
            old_name='TaxonomyOrder',
            new_name='Order',
        ),
        migrations.AddField(
            model_name='showsearchfields',
            name='Genus',
            field=models.BooleanField(default=False, verbose_name=' _Tax. Family'),
        ),
        migrations.AddField(
            model_name='showsearchfields',
            name='Phyum',
            field=models.BooleanField(default=False, verbose_name=' _Tax. Phyum'),
        ),
        migrations.AddField(
            model_name='showsearchfields',
            name='SubClass',
            field=models.BooleanField(default=False, verbose_name=' _Tax. Class'),
        ),
        migrations.AddField(
            model_name='showsearchfields',
            name='SubPhyum',
            field=models.BooleanField(default=False, verbose_name=' _Tax. Phyum'),
        ),
    ]
