# Generated by Django 3.0 on 2021-04-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0010_auto_20210427_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showsearchfields',
            name='Genus',
            field=models.BooleanField(default=False, verbose_name=' _Tax. Genus'),
        ),
        migrations.AlterField(
            model_name='showsearchfields',
            name='Kingdom',
            field=models.BooleanField(default=False, verbose_name=' _Tax. Kingdom'),
        ),
        migrations.AlterField(
            model_name='showsearchfields',
            name='SubClass',
            field=models.BooleanField(default=False, verbose_name=' _Tax. SubClass'),
        ),
        migrations.AlterField(
            model_name='showsearchfields',
            name='SubPhyum',
            field=models.BooleanField(default=False, verbose_name=' _Tax. SubPhyum'),
        ),
    ]
