# Generated by Django 3.0 on 2021-04-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0011_auto_20210427_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='ShowTaxonomy',
        ),
        migrations.AddField(
            model_name='show',
            name='ShowClassification',
            field=models.BooleanField(default=False, verbose_name=' _Classification'),
        ),
    ]
