# Generated by Django 3.0 on 2021-05-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0012_auto_20210427_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='showsearchfields',
            name='StatusUKOccurences',
            field=models.BooleanField(default=False, verbose_name=' _UK Occurences'),
        ),
    ]
