# Generated by Django 3.0 on 2021-05-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0013_showsearchfields_statusukoccurences'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='ShowNonUKOccurences',
            field=models.BooleanField(default=False, verbose_name=' _Comments'),
        ),
    ]
