# Generated by Django 3.0 on 2021-05-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0014_show_shownonukoccurences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='ShowNonUKOccurences',
            field=models.BooleanField(default=False, verbose_name=' _UK Occurences'),
        ),
    ]
