# Generated by Django 3.0 on 2021-05-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0015_auto_20210511_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='ShowNonUKOccurences',
        ),
        migrations.AddField(
            model_name='show',
            name='ShowUKOccurences',
            field=models.BooleanField(default=False, verbose_name=' _UK Species Only'),
        ),
    ]
