# Generated by Django 3.0 on 2021-05-14 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0016_auto_20210511_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='ShowUKOccurences',
            new_name='ShowOnlyUKOccurences',
        ),
    ]
