# Generated by Django 3.0 on 2021-05-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0017_auto_20210514_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showsearchfields',
            name='HabitatAssociations',
            field=models.BooleanField(default=False, verbose_name=' _Associated Trees'),
        ),
    ]
