# Generated by Django 3.0 on 2021-05-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0018_auto_20210516_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='ShowMacromycetes',
            field=models.BooleanField(default=False, verbose_name=' _Macromycetes (Large fungi) Only'),
        ),
    ]
