# Generated by Django 3.0 on 2021-05-20 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0019_show_showmacromycetes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showsearchfields',
            name='StatusUKOccurences',
        ),
    ]
