# Generated by Django 3.0 on 2021-06-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0020_remove_showsearchfields_statusukoccurences'),
    ]

    operations = [
        migrations.AddField(
            model_name='showsearchfields',
            name='ExactMatch',
            field=models.BooleanField(default=False, verbose_name=' _Exact match'),
        ),
    ]
