# Generated by Django 3.0 on 2021-07-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0021_showsearchfields_exactmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='showsearchfields',
            name='HabitatGrowingMedium',
            field=models.BooleanField(default=False, verbose_name=' _Growing Medium'),
        ),
    ]
