# Generated by Django 3.0 on 2021-07-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitat',
            name='GrowingMedium',
            field=models.CharField(blank=True, default='NoData', max_length=255, null=True),
        ),
    ]
